
# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN apt-get update \
    && apt-get -y install libpq-dev gcc

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 3000 available to the world outside this container
EXPOSE 3000

ENV ISDOCKER=1

# Run flask app
CMD flask run --host=0.0.0.0 --port=3000 --debug